spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:124.222.121.252:8848}
        namespace: db3d5d0c-8625-4b26-858b-c852544930f5
  data:
    redis:
      host: 124.222.121.252
      port: 6379
      password: xugang1998
      timeout: 3000
      database: 0